project-excludes = [
    "**/EXTERNAL",
    "**/__pycache__",
    "**/.vincent",
    "**/.venv_new",
    "**/data",
    "**/.venv",
    "**/.venv_alt",
    "**/.venv_green",
    "**/.classpath",
    "**/.factorypath",
    "**/.ipynb_checkpoints",
    "**/CVS",
    "**/.venv_*",
    "**/.svn",
    "**/.venv_UV",
    "**/dist",
    "**/.virtual_documents",
    "**/.mypy_cache",
    "**/.idea",
    "**/*.asv",
    "**/.git",
    "**/.spyproject",
    "**/docs",
    "**/.venv_black",
    "**/.project",
    "**/.venv_teal",
    "**/.venv_white",
    "**/scratchpads",
    "**/node_modules",
    "**/.dvc",
    "**/._cell_execution_logs",
    "**/build",
    "**/LibrariesExamples",
    "**/.settings",
    "**/.venv_raw",
    "**/.vscode",
    "**/templating",
    "**/.hg",
    "**/.venv_yellow",
    '**/site-packages/**\*',
    "**/output",
    "**/SCRATCH",
]
python-version = "3.9.0"
infer-with-first-use = false

[errors]
missing-import = "error"
untyped-import = "ignore"
